dataset:
  class: datasets.ShotsDataset
  data_root: 'C:/CXFLOW/Dataset'

model:
  name: ShotsExample
  class: shots_convnet.ShotsConvNet
  n_gpus: 1

  optimizer:
    class: AdamOptimizer
    learning_rate: 0.001

  inputs: [images, labels]
  outputs: [loss, frame_accuracy, predictions, sequence_accuracy, f1, precision, recall]
  restore_fallback: cxflow_tensorflow.BaseModel

main_loop:
  extra_streams: [test]
  skip_zeroth_epoch: true
  buffer: 4

hooks:
  - ShowProgress
  - ComputeStats:
      variables:
        - loss
        - f1 : [nanmean, nanfraction]
        - frame_accuracy
        - sequence_accuracy
        - precision : [nanmean, nanfraction]
        - recall : [nanmean, nanfraction]
  - LogVariables
  - LogProfile
  - SaveLatest
  - StopAfter:
      epochs: 50
  - cxflow_tensorflow.hooks.WriteTensorBoard
predict:
  model:
    inputs: [images]
    outputs: [predictions]
  hooks:
    - shots_convnet.ShotsPredict
    - ShowProgress
    - LogProfile